package p8499.style.xml

import p8499.style.color.Color
import javax.xml.transform.sax.TransformerHandler

interface Node {
    fun output(handler: TransformerHandler)
}

fun String.node(): Node = Text(this)

fun set(vararg attrs: Pair<String, String>): Tag = Tag("set", *attrs)
fun set(ordering: String): Tag = set(android_ordering(ordering))
fun shape(vararg attrs: Pair<String, String>): Tag = Tag("shape", *attrs)
fun rectangle(vararg attrs: Pair<String, String>): Tag = shape(android_shape("rectangle"), *attrs)
fun oval(vararg attrs: Pair<String, String>): Tag = shape(android_shape("oval"), *attrs)
fun ring(vararg attrs: Pair<String, String>): Tag = shape(android_shape("ring"), *attrs)
fun line(vararg attrs: Pair<String, String>): Tag = shape(android_shape("line"), *attrs)
fun solid(vararg attrs: Pair<String, String>): Tag = Tag("solid", *attrs)
fun solid(color: Color): Tag = solid(android_color(color))
fun size(vararg attrs: Pair<String, String>): Tag = Tag("size", *attrs)
fun size(width: String, height: String): Tag = size(android_width(width), android_height(height))
fun padding(vararg attrs: Pair<String, String>): Tag = Tag("padding", *attrs)
fun padding(top: String, bottom: String, left: String, right: String): Tag = padding(android_top(top), android_bottom(bottom), android_left(left), android_right(right))
fun padding(padding: String) = padding(android_top(padding), android_bottom(padding), android_left(padding), android_right(padding))
fun corners(vararg attrs: Pair<String, String>): Tag = Tag("corners", *attrs)
fun corners(topLeftRadius: String, topRightRadius: String, bottomLeftRadius: String, bottomRightRadius: String): Tag = corners(android_topLeftRadius(topLeftRadius), android_topRightRadius(topRightRadius), android_bottomLeftRadius(bottomLeftRadius), android_bottomRightRadius(bottomRightRadius))
fun corners(radius: String): Tag = corners(android_radius(radius))
fun stroke(vararg attrs: Pair<String, String>): Tag = Tag("stroke", *attrs)
fun stroke(color: Color, width: String): Tag = stroke(android_color(color), android_width(width))
fun stroke(color: Color, width: String, dashWidth: String, dashGap: String): Tag = stroke(android_color(color), android_width(width), android_dashWidth(dashWidth), android_dashGap(dashGap))
fun gradient(vararg attrs: Pair<String, String>): Tag = Tag("gradient", *attrs)
fun item(vararg attrs: Pair<String, String>): Tag = Tag("item", *attrs)
fun layer_list(vararg attrs: Pair<String, String>): Tag = Tag("layer-list", *attrs)
fun objectAnimator(vararg attrs: Pair<String, String>): Tag = Tag("objectAnimator", *attrs)
fun animator(vararg attrs: Pair<String, String>): Tag = Tag("animator", *attrs)
fun propertyValuesHolder(vararg attrs: Pair<String, String>): Tag = Tag("propertyValuesHolder", *attrs)
fun vector(vararg attrs: Pair<String, String>): Tag = Tag("vector", *attrs)
fun path(vararg attrs: Pair<String, String>): Tag = Tag("path", *attrs)


fun android_ordering(v: Any?) = "android:ordering" to (v?.toString() ?: "@null")
fun android_shape(v: Any?) = "android:shape" to (v?.toString() ?: "@null")
fun android_top(v: Any?) = "android:top" to (v?.toString() ?: "@null")
fun android_bottom(v: Any?) = "android:bottom" to (v?.toString() ?: "@null")
fun android_left(v: Any?) = "android:left" to (v?.toString() ?: "@null")
fun android_right(v: Any?) = "android:right" to (v?.toString() ?: "@null")
fun android_color(v: Any?) = "android:color" to (v?.toString() ?: "@null")
fun android_width(v: Any?) = "android:width" to (v?.toString() ?: "@null")
fun android_height(v: Any?) = "android:height" to (v?.toString() ?: "@null")
fun android_radius(v: Any?) = "android:radius" to (v?.toString() ?: "@null")
fun android_topLeftRadius(v: Any?) = "android:topLeftRadius" to (v?.toString() ?: "@null")
fun android_topRightRadius(v: Any?) = "android:topRightRadius" to (v?.toString() ?: "@null")
fun android_bottomLeftRadius(v: Any?) = "android:bottomLeftRadius" to (v?.toString() ?: "@null")
fun android_bottomRightRadius(v: Any?) = "android:bottomRightRadius" to (v?.toString() ?: "@null")
fun android_dashGap(v: Any?) = "android:dashGap" to (v?.toString() ?: "@null")
fun android_dashWidth(v: Any?) = "android:dashWidth" to (v?.toString() ?: "@null")
fun android_angle(v: Any?) = "android:angle" to (v?.toString() ?: "@null")
fun android_centerColor(v: Any?) = "android:centerColor" to (v?.toString() ?: "@null")
fun android_centerX(v: Any?) = "android:centerX" to (v?.toString() ?: "@null")
fun android_centerY(v: Any?) = "android:centerY" to (v?.toString() ?: "@null")
fun android_endColor(v: Any?) = "android:endColor" to (v?.toString() ?: "@null")
fun android_gradientRadius(v: Any?) = "android:gradientRadius" to (v?.toString() ?: "@null")
fun android_startColor(v: Any?) = "android:startColor" to (v?.toString() ?: "@null")
fun android_type(v: Any?) = "android:type" to (v?.toString() ?: "@null")
fun android_useLevel(v: Any?) = "android:useLevel" to (v?.toString() ?: "@null")
fun android_interpolator(v: Any?) = "android:interpolator" to (v?.toString() ?: "@null")
fun android_pathData(v: Any?) = "android:pathData" to (v?.toString() ?: "@null")
fun android_propertyName(v: Any?) = "android:propertyName" to (v?.toString() ?: "@null")
fun android_propertyXName(v: Any?) = "android:propertyXName" to (v?.toString() ?: "@null")
fun android_propertyYName(v: Any?) = "android:propertyYName" to (v?.toString() ?: "@null")
fun android_valueFrom(v: Any?) = "android:valueFrom" to (v?.toString() ?: "@null")
fun android_valueTo(v: Any?) = "android:valueTo" to (v?.toString() ?: "@null")
fun android_valueType(v: Any?) = "android:valueType" to (v?.toString() ?: "@null")
fun android_duration(v: Any?) = "android:duration" to (v?.toString() ?: "@null")
fun android_repeatCount(v: Any?) = "android:repeatCount" to (v?.toString() ?: "@null")
fun android_repeatMode(v: Any?) = "android:repeatMode" to (v?.toString() ?: "@null")
fun android_startOffset(v: Any?) = "android:startOffset" to (v?.toString() ?: "@null")
fun android_viewportWidth(v: Any?) = "android:viewportWidth" to (v?.toString() ?: "@null")
fun android_viewportHeight(v: Any?) = "android:viewportHeight" to (v?.toString() ?: "@null")
fun android_name(v: Any?) = "android:name" to (v?.toString() ?: "@null")
fun android_alpha(v: Any?) = "android:alpha" to (v?.toString() ?: "@null")
fun android_autoMirrored(v: Any?) = "android:autoMirrored" to (v?.toString() ?: "@null")
fun android_tint(v: Any?) = "android:tint" to (v?.toString() ?: "@null")
fun android_tintMode(v: Any?) = "android:tintMode" to (v?.toString() ?: "@null")
fun android_fillColor(v: Any?) = "android:fillColor" to (v?.toString() ?: "@null")
fun android_strokeColor(v: Any?) = "android:strokeColor" to (v?.toString() ?: "@null")
fun android_strokeWidth(v: Any?) = "android:strokeWidth" to (v?.toString() ?: "@null")
fun android_fillAlpha(v: Any?) = "android:fillAlpha" to (v?.toString() ?: "@null")
fun android_fillType(v: Any?) = "android:fillType" to (v?.toString() ?: "@null")
fun android_strokeAlpha(v: Any?) = "android:strokeAlpha" to (v?.toString() ?: "@null")
fun android_strokeLineCap(v: Any?) = "android:strokeLineCap" to (v?.toString() ?: "@null")
fun android_strokeLineJoin(v: Any?) = "android:strokeLineJoin" to (v?.toString() ?: "@null")
fun android_strokeMiterLimit(v: Any?) = "android:strokeMiterLimit" to (v?.toString() ?: "@null")
fun android_trimPathStart(v: Any?) = "android:trimPathStart" to (v?.toString() ?: "@null")
fun android_trimPathEnd(v: Any?) = "android:trimPathEnd" to (v?.toString() ?: "@null")
fun android_trimPathOffset(v: Any?) = "android:trimPathOffset" to (v?.toString() ?: "@null")
